# Install VSCode extensions. Using --force updates them.
code --install-extension adamwalzer.scss-lint --force
code --install-extension castwide.solargraph --force
code --install-extension CraigMaslowski.erb --force
code --install-extension misogi.ruby-rubocop --force
code --install-extension mrmlnc.vscode-scss --force
code --install-extension pavlitsky.yard --force
code --install-extension rebornix.ruby --force
code --install-extension shanehofstetter.rails-i18n --force
code --install-extension vortizhe.simple-ruby-erb --force
code --install-extension wayou.vscode-todo-highlight --force
code --install-extension yzhang.markdown-all-in-one --force
code --install-extension kbysiec.vscode-search-everywhere --force
code --install-extension wingrunr21.vscode-ruby --force
code --install-extension equinusocio.vsc-community-material-theme --force
code --install-extension serayuzgur.crates --force
code --install-extension eamodio.gitlens --force
code --install-extension k--kato.intellij-idea-keybindings --force
code --install-extension ms-vsliveshare.vsliveshare --force
code --install-extension sumneko.lua --force
code --install-extension yzhang.markdown-all-in-one --force
code --install-extension ms-ossdata.vscode-postgresql --force
code --install-extension shanehofstetter.rails-i18n --force
code --install-extension hridoy.rails-snippets --force
code --install-extension rust-lang.rust --force
code --install-extension tejanium.stimulusjs --force
code --install-extension jcbuisson.vue --force